# app/config/routing.yml
fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
  prefix: account/

#used when referencing the routing.yml in the src folder as external routing
product_default:
  resource: "@ProductDefaultBundle/Resources/config/routing.yml"
  prefix: /
  options:
    expose: true

#used when routing is handled by the controller itself
# app:
#   resource: "@ProductDefaultBundle/Controller/"
#   type: annotation